name: Build Silverblue Custom ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build image + ISO via BlueBuild
      uses: blue-build/github-action@v1.9.1
      with:
        recipe: recipes/silverblue-custom.yml
        # You can also pass other inputs if needed, e.g. signing, registry, etc.
        # registry_username: ${{ secrets.REG_USERNAME }}
        # registry_token: ${{ secrets.REG_TOKEN }}
      # Optionally set env vars, etc.

    - name: Find built ISO
      run: |
        mkdir -p artifact
        # adjust this glob to match where bluebuild outputs the ISO
        # e.g. output/isos or whatever your recipe defines
        cp output/isos/*.iso artifact/

    - name: Upload ISO artifact (v4)
      uses: actions/upload-artifact@v3
      with:
        name: silverblue-custom-installer‑v4
        path: artifact/*.iso

