# .github/workflows/build‑iso.yml

name: Build Silverblue Custom ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # if using secrets for signing or registry
      secrets: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup BlueBuild (if required)
      - name: Install BlueBuild CLI
        run: |
          curl -LO https://github.com/ublue-os/bluebuild/releases/download/v0.1.0/bluebuild-linux-amd64
          chmod +x bluebuild-linux-amd64
          sudo mv bluebuild-linux-amd64 /usr/local/bin/bluebuild

      - name: Build image and ISO
        uses: ublue-os/blue-build/github-action@v1
        with:
          recipe: recipes/silverblue-custom.yml
          # Signing / registry often needed; skip or use dummy
          # cosign_private_key: ${{ secrets.COSIGN_KEY }}
          # registry_token: ${{ secrets.REG_TOKEN }}
          # registry_username: your_user
        # optionally set env vars for environment

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v3
        with:
          name: silverblue-custom-installer-iso
          path: |
            output/isos/*.iso
            # adjust to where the ISO is generated
