name: Build Custom Silverblue ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman curl jq coreutils tree

      - name: Set up cosa environment
        run: |
          mkdir -p build/src/config
          tree .
          cp image/ostree/config.yaml build/src/config/manifest.yaml
          cp image/ignition/config.yaml build/ignition-config.yaml

      - name: Run cosa init
        run: |
          podman run --rm \
            -v ${{ github.workspace }}/build:/srv:z \
            --workdir /srv \
            quay.io/coreos-assembler/coreos-assembler:latest \
            cosa init
            
      - name: Run cosa fetch
        run: |
          podman run --rm \
            -v ${{ github.workspace }}/build:/srv:z \
            --workdir /srv \
            quay.io/coreos-assembler/coreos-assembler:latest \
            cosa fetch
            
      - name: Run cosa build
        run: |
          podman run --rm \
            -v ${{ github.workspace }}/build:/srv:z \
            --workdir /srv \
            quay.io/coreos-assembler/coreos-assembler:latest \
            cosa build
  
      - name: Run cosa buildextend-installer
        run: |
          podman run --rm \
            -v ${{ github.workspace }}/build:/srv:z \
            --workdir /srv \
            quay.io/coreos-assembler/coreos-assembler:latest \
            cosa buildextend-installer
    
      - name: Run cosa butane
        run: |
          podman run --rm \
            -v ${{ github.workspace }}/build:/srv:z \
            --workdir /srv \
            quay.io/coreos-assembler/coreos-assembler:latest \
            butane ignition-config.yaml -o ignition/config.ign

      - name: Run cosa coreos-installer iso customize
        run: |
          podman run --rm \
            -v ${{ github.workspace }}/build:/srv:z \
            --workdir /srv \
            quay.io/coreos-assembler/coreos-assembler:latest \
            coreos-installer iso customize \
                --dest-ignition ignition/config.ign \
                -o custom-silverblue.iso $(ls builds/latest/*.iso | head -n1)
  
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: custom-silverblue-iso
          path: build/custom-silverblue.iso
