name: Build Custom Silverblue ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y podman curl jq coreutils

      - name: Download cosa CLI (correctly)
        run: |
          # Get latest release tag
          COSA_VERSION=$(curl -s https://api.github.com/repos/coreos/coreos-assembler/releases/latest | jq -r .tag_name)

          # Download the actual binary
          curl -L -o cosa "https://github.com/coreos/coreos-assembler/releases/download/${COSA_VERSION}/coreos-assembler-${COSA_VERSION}-x86_64"

          chmod +x cosa
          sudo mv cosa /usr/local/bin/cosa

      - name: Initialize cosa project
        run: |
          cosa init

      - name: Add config files
        run: |
          mkdir -p src/config
          cp image/ostree/config.yaml src/config/manifest.yaml
          cp image/ignition/config.yaml ignition-config.yaml

      - name: Fetch sources
        run: |
          cosa fetch

      - name: Build OSTree commit
        run: |
          cosa build

      - name: Build installer ISO
        run: |
          cosa buildextend-installer

      - name: Install Butane
        run: |
          curl -LO https://github.com/coreos/butane/releases/latest/download/butane-x86_64-unknown-linux-gnu
          chmod +x butane-x86_64-unknown-linux-gnu
          sudo mv butane-x86_64-unknown-linux-gnu /usr/local/bin/butane

      - name: Generate Ignition config
        run: |
          mkdir -p ignition
          butane image/ignition/config.yaml -o ignition/config.ign

      - name: Install coreos-installer
        run: |
          curl -LO https://github.com/coreos/coreos-installer/releases/latest/download/coreos-installer-x86_64
          chmod +x coreos-installer-x86_64
          sudo mv coreos-installer-x86_64 /usr/local/bin/coreos-installer

      - name: Embed Ignition into ISO
        run: |
          ISO=$(ls builds/latest/*.iso | head -n1)
          cp "$ISO" original.iso
          coreos-installer iso customize \
            --dest-ignition ignition/config.ign \
            -o custom-silverblue.iso original.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: custom-silverblue-iso
          path: custom-silverblue.iso
