name: Build Silverblue Custom ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Disable signing
      run: echo "--no-sign" >> "$GITHUB_ENV"

    - name: Build image + ISO via BlueBuild
      uses: blue-build/github-action@v1.9.1
      with:
        recipe: recipes/silverblue-custom.yml
        build_opts: ${{ env.BUILD_OPTS }}

    - name: Find built ISO
      run: |
        mkdir -p artifact
        # adjust this glob to match where bluebuild outputs the ISO
        # e.g. output/isos or whatever your recipe defines
        cp output/isos/*.iso artifact/

    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: silverblue-custom-installer
        path: artifact/*.iso

